name: format

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "ui/**"

concurrency:
  group: build-format-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ruff-format:
    name: "Python code quality checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.10

      - name: Install development dependencies
        working-directory: pipecat
        run: uv sync --group dev

      - name: Ruff formatter
        id: ruff-format
        working-directory: pipecat
        run: uv run ruff format --diff

      - name: Ruff linter (all rules)
        id: ruff-check
        working-directory: pipecat
        run: uv run ruff check

  prettier-format:
    name: "TypeScript code quality checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ui
        run: npm install

      - name: Prettier formatter
        id: prettier-format
        working-directory: ui
        run: npx prettier --check "src/**/*.{css,ts,tsx}"
